
[[main]]
  name = "News"
  url = "/news/"
  weight = 10

[[main]]
  name = "Projects"
  url = "/project/"
  weight = 20

[[main]]
  name = "Publications"
  url = "/publication/"
  weight = 30

[[main]]
  name = "Education"
  url = "/education/"
  weight = 40

[[main]]
  name = "Awards"
  url = "/award/"
  weight = 50
